spring:


  datasource:
    url: jdbc:mysql://localhost:3306/gym_management_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    cache: false


#server:
#  port: 8888

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.astfitness.pojo